= CodeReady Toolchain

This repo is for controllers, libs, scripts, make files, etc to be shared between host and member operators.

== Configuring developers.redhat.com Authentication in OpenShift 4 Cluster

Create a secret with Identity Provider credentials:
```
$ oc apply -f deploy/idp_secret.yaml
```
Create an Identity Provider:
```
$ oc apply -f deploy/idp.yaml
```

== Creating User

Create a user, identity and user identity mapping:
```
$ oc apply -f deploy/user.yaml
```

== Scripts

=== add-cluster.sh

The CodeReady Toolchain architecture contains two types of clusters `host` and `member`.
To connect these two clusters together it is necessary to run a script link:scripts/add-cluster.sh[] that takes two arguments:

1. type of the cluster to be added
2. name of the cluster to be added

The script is working with Minishift profiles and expects that there are two clusters (profiles) called `host` and `member`.
To be able to run the script, you need to have both clusters prepared, which means:

- created CRDs
- created ServiceAccount with ClusterRole/ClusterRoleBinding

When the script is executed with parameters `add-cluster.sh member member-cluster` then it does these steps:

1. goes to the `member` profile
2. takes a secret of the SA (from the `member`)
3. takes API endpoint of the `member` cluster from Kube config
4. goes to `host` profile
5. creates a secret with the SA token taken from the `member`
6. creates `KubeFedCluster` CR representing the added `member`
